services:
  streamlit:
    build: .
    ports:
      - "8443:8501"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
      - ../FinalizedPpipelines:/FinalizedPpipelines
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
